(() => {
  "use strict";
  const DB_NAME = "answersearch-db", STORE = "banks", DB_VERSION = 1;
  const els = Object.fromEntries(["uploadPanel","dropZone","fileInput","loadError","workspace","bankCount","bankList","searchInput","resetSearchBtn","typeFilter","fileSummary","resultSummary","emptyState","noResult","results","firstUse","addBankBtn","asideAddBtn","firstAddBtn","closeUploadBtn"].map(id => [id, document.getElementById(id)]));
  let banks = [], activeBankId = "", db;
  const aliases = {type:["类型","题型","type","questiontype","题目类型"],question:["题干","题目","问题","question","title","content"],answer:["答案","正确答案","参考答案","answer","correctanswer"],explanation:["解析","答案解析","说明","explanation","analysis"],optionA:["选项a","a","optiona","答案a"],optionB:["选项b","b","optionb","答案b"],optionC:["选项c","c","optionc","答案c"],optionD:["选项d","d","optiond","答案d"],optionE:["选项e","e","optione","答案e"],optionF:["选项f","f","optionf","答案f"]};
  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:"id"});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  function dbGetAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});}
  function dbPut(bank){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(bank);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
  function dbDelete(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
  const normalizeHeader=v=>String(v??"").trim().toLowerCase().replace(/[\s_\-—（）()【】[\]：:]/g,"");
  const normalize=v=>String(v??"").toLowerCase().replace(/\s+/g,"");
  function pinyinText(v){try{return window.pinyinPro?.pinyin(String(v??""),{toneType:"none",type:"array"}).join("").toLowerCase()||"";}catch{return"";}}
  function getValue(row,key){const map=Object.fromEntries(Object.entries(row).map(([k,v])=>[normalizeHeader(k),v]));for(const name of aliases[key]){const v=map[normalizeHeader(name)];if(v!==undefined&&v!==null&&String(v).trim()!=="")return String(v).trim();}return"";}
  function normalizeRows(rows){return rows.map((row,i)=>{const options=["optionA","optionB","optionC","optionD","optionE","optionF"].map(k=>getValue(row,k));const q=getValue(row,"question"),a=getValue(row,"answer"),ex=getValue(row,"explanation"),raw=getValue(row,"type").toLowerCase();const type=raw.includes("选择")||raw.includes("单选")||raw.includes("多选")||raw.includes("choice")||options.some(Boolean)?"choice":"qa";const searchText=[q,a,ex,...options].join(" ");return{id:i+1,type,question:q,options,answer:a,explanation:ex,searchText:normalize(searchText),pinyinText:pinyinText(searchText)};}).filter(x=>x.question||x.answer);}
  function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell="";}else cell+=c;}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);if(!rows.length)return[];const h=rows[0].map(v=>String(v).trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??""])));}
  async function readFile(file){const ext=file.name.split(".").pop().toLowerCase();if(ext==="csv")return parseCsv(await file.text());if(!window.XLSX)throw new Error("Excel 解析组件加载失败，请检查网络或改用 CSV。");const book=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false});if(!book.SheetNames.length)throw new Error("文件中没有可读取的工作表。");return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:"",raw:false});}
  async function handleFiles(files){hideError();for(const file of [...files]){const ext=file.name.split(".").pop().toLowerCase();if(!["xlsx","xls","csv"].includes(ext)){showError(`${file.name} 格式不支持`);continue;}try{const questions=normalizeRows(await readFile(file));if(!questions.length)throw new Error("未识别到有效题目");const existing=banks.find(b=>b.name===file.name);const bank={id:existing?.id||uid(),name:file.name,questions,updatedAt:Date.now()};await dbPut(bank);banks=banks.filter(b=>b.id!==bank.id).concat(bank).sort((a,b)=>b.updatedAt-a.updatedAt);activeBankId=bank.id;}catch(err){showError(`${file.name}：${err.message||"解析失败"}`);}}els.fileInput.value="";closeUpload();render();}
  function activeBank(){return banks.find(b=>b.id===activeBankId)||banks[0];}
  function render(){const has=banks.length>0;els.firstUse.classList.toggle("hidden",has);els.workspace.classList.toggle("hidden",!has);if(!has){els.uploadPanel.classList.add("hidden");return;}if(!activeBankId)activeBankId=banks[0].id;els.bankCount.textContent=`${banks.length} 个`;els.bankList.innerHTML=banks.map(b=>`<div class="bank-item ${b.id===activeBankId?"active":""}" data-id="${b.id}"><button class="bank-select" type="button"><strong>${esc(b.name)}</strong><span>${b.questions.length} 题 · ${new Date(b.updatedAt).toLocaleDateString()}</span></button><button class="bank-delete" type="button" aria-label="删除题库" data-delete="${b.id}">×</button></div>`).join("");const bank=activeBank();els.fileSummary.textContent=`${bank.name} · 共 ${bank.questions.length} 题`;search();}
  function tokens(){return els.searchInput.value.trim().split(/\s+/).filter(Boolean);}
  function search(){const bank=activeBank();if(!bank)return;const raw=tokens(),terms=raw.map(x=>({raw:x,n:normalize(x),p:normalize(pinyinText(x))})),type=els.typeFilter.value;els.resetSearchBtn.classList.toggle("hidden",!raw.length);if(!terms.length){els.results.innerHTML="";els.noResult.classList.add("hidden");els.emptyState.classList.remove("hidden");els.resultSummary.textContent="请输入关键词";return;}const matched=bank.questions.filter(q=>(type==="all"||q.type===type)&&terms.every(t=>q.searchText.includes(t.n)||q.pinyinText.includes(t.n)||q.pinyinText.includes(t.p)));els.emptyState.classList.add("hidden");els.resultSummary.textContent=`命中 ${matched.length} 题`;if(!matched.length){els.results.innerHTML="";els.noResult.classList.remove("hidden");return;}els.noResult.classList.add("hidden");els.results.innerHTML=matched.map((q,i)=>card(q,i,raw)).join("");}
  function highlight(value,terms){let html=esc(value);const sorted=[...terms].filter(t=>/[\u3400-\u9fffA-Za-z0-9]/.test(t)).sort((a,b)=>b.length-a.length);for(const term of sorted){const safe=esc(term).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");try{html=html.replace(new RegExp(`(${safe})`,"gi"),"<mark>$1</mark>");}catch{}}return html;}
  function card(q,i,terms){const opts=q.options.map((o,j)=>({o,l:String.fromCharCode(65+j)})).filter(x=>x.o).map(x=>`<div class="option"><span class="option-label">${x.l}.</span>${highlight(x.o,terms)}</div>`).join("");return`<article class="question-card"><div class="question-main"><div class="question-head"><span class="number">${i+1}</span><span class="badge">${q.type==="choice"?"选择题":"问答题"}</span><div class="question-text">${highlight(q.question,terms)}</div></div>${opts?`<div class="options">${opts}</div>`:""}</div><div class="answer-block"><div class="answer-title">答案</div><div class="answer-content">${highlight(q.answer||"未填写",terms)}</div></div>${q.explanation?`<div class="explanation"><strong>解析</strong>${highlight(q.explanation,terms)}</div>`:""}</article>`;}
  function openUpload(){els.uploadPanel.classList.remove("hidden");els.uploadPanel.scrollIntoView({behavior:"smooth",block:"start"});}
  function closeUpload(){els.uploadPanel.classList.add("hidden");hideError();}
  function showError(msg){els.loadError.textContent=msg;els.loadError.classList.remove("hidden");}
  function hideError(){els.loadError.textContent="";els.loadError.classList.add("hidden");}
  [els.addBankBtn,els.asideAddBtn,els.firstAddBtn].forEach(b=>b.addEventListener("click",openUpload));els.closeUploadBtn.addEventListener("click",closeUpload);
  els.dropZone.addEventListener("click",()=>els.fileInput.click());els.dropZone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();els.fileInput.click();}});els.fileInput.addEventListener("change",e=>handleFiles(e.target.files));
  ["dragenter","dragover"].forEach(n=>els.dropZone.addEventListener(n,e=>{e.preventDefault();els.dropZone.classList.add("dragover");}));["dragleave","drop"].forEach(n=>els.dropZone.addEventListener(n,e=>{e.preventDefault();els.dropZone.classList.remove("dragover");}));els.dropZone.addEventListener("drop",e=>handleFiles(e.dataTransfer.files));
  els.bankList.addEventListener("click",async e=>{const del=e.target.closest("[data-delete]");if(del){e.stopPropagation();const id=del.dataset.delete;if(confirm("确认删除这个本地题库？")){await dbDelete(id);banks=banks.filter(b=>b.id!==id);if(activeBankId===id)activeBankId=banks[0]?.id||"";render();}return;}const item=e.target.closest(".bank-item");if(item){activeBankId=item.dataset.id;render();}});
  els.searchInput.addEventListener("input",search);els.typeFilter.addEventListener("change",search);els.resetSearchBtn.addEventListener("click",()=>{els.searchInput.value="";search();els.searchInput.focus();});document.addEventListener("keydown",e=>{if(e.key==="/"&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();els.searchInput.focus();}});
  (async()=>{try{db=await openDb();banks=(await dbGetAll()).sort((a,b)=>b.updatedAt-a.updatedAt);activeBankId=banks[0]?.id||"";render();}catch{showError("浏览器本地存储初始化失败，请确认未处于严格隐私模式。");els.firstUse.classList.remove("hidden");}})();
})();
